[project]
name = "avaliacao-2tri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ju-Petersen", email = "juliapetersenavi@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
avaliacao-2tri = "avaliacao_2tri:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
