[project]
name = "avaliacao-2tri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe5804", email = "felipebucci2208@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=26.7.0",
]

[project.scripts]
avaliacao-2tri = "avaliacao_2tri:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
